### ISSUE TITLE
it should only show the log relating to the task

### ISSUE THREAD

**Issue by da-liii** [sequentialread/tickscript-studio#1]
may be grepped by task name

**Comment by forestjohnsonpeoplenet** [comment]
Currently the process is as follows:

1. aquire a lock for the current user, display an error and abort if the lock is already held.
2. delete the current task from kapacitor
3. clear the log file
4. create the new task 
5. write the test data 
6. poll for results for 1 minute or until the user clicks the stop button
7. release the lock

If you are seeing old lines or other lines in the log chances are you are using this tool incorrectly. Maybe it is unable to clear the log file due to permissions issue or misconfiguration. 

I agree that grepping the task name would be a quick and easy fix for this. I will consider it, also, feel free to make a PR with that change if it works for you.

In the future kapacitor may provide an API endpoint for reading logs and I will definitely use that when/if it is avaliable.
